version: "3.9"

services:
  django:
    build:
      context: ./slashTeam          # فقط از فولدر backend بیلد کن
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080

    ports:
      - "8080:8080"

    restart: always

  react:
    build:
      context: ./UI         # فقط از فولدر frontend بیلد کن
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - /app/node_modules           # این خط خیلی مهمه! node_modules رو خراب نکنه
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true    # برای hot reload داخل داکر
    restart: always