version: "3.9"

services:
  django:
    build:
      context: ./slashTeam
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONDONTWRITEBYTECCODE=1
      - PYTHONNONBUFFERED=1
    volumes:
      - ./slashTeam:/app
    ports:
      - "8000:8000"

    expose:
      - "8000"

    restart: always

  react:
    build:
      context: ./UI         # فقط از فولدر frontend بیلد کن
      dockerfile: ./SlashFront
    command: npm start
    volumes:
      - /app/node_modules           # این خط خیلی مهمه! node_modules رو خراب نکنه
      - ./UI:/app

    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true    # برای hot reload داخل داکر
    restart: always
    depends_on:
      - django