version: "3.9"

services:
  django:
    build:
      context: ./slashTeam
      dockerfile: Dockerfile
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120

    environment:
      - PYTHONDONTWRITEBYTECCODE=1
      - PYTHONNONBUFFERED=1
    volumes:
      - ./slashTeam:/app
    expose:
      - "8000"
    restart: always

  react:
    build:
      context: ./slashFront         # فقط از فولدر frontend بیلد کن
      dockerfile: Dockerfile
    command: npx serve -s build
    volumes:
      - /app/node_modules           # این خط خیلی مهمه! node_modules رو خراب نکنه
      - ./slashFront:/app

    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true    # برای hot reload داخل داکر
    restart: always
    depends_on:
      - django

  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - react