events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://react:3000;
    }

    location /admin/ {
      proxy_pass http://django:8000;
    }
    location /swagger/ {
      proxy_pass http://django:8000;
    }
    location /about-team/ {
      proxy_pass http://django:8000;
    }
    location /comments/ {
      proxy_pass http://django:8000;
    }
    location /contact/ {
      proxy_pass http://django:8000;
    }
    location /members/ {
      proxy_pass http://django:8000;
    }
    location /service/ {
      proxy_pass http://django:8000;
    }
    location /site/ {
      proxy_pass http://django:8000;
    }
    location /static/ {
      proxy_pass http://react:3000;
    }
    location /static-files/ {
      proxy_pass http://django:8000;
    }
  }
}
