# Generated by Django 5.2 on 2025-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_team', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about',
            field=models.TextField(default=1, verbose_name='درباره ما'),
            preserve_default=False,
        ),
    ]
