# Generated by Django 5.2 on 2025-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_team', '0003_about_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(),
        ),
    ]
