# Generated by Django 5.2 on 2025-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.TextField(blank=True, null=True, verbose_name='لینک ایکون'),
        ),
    ]
