# Generated by Django 5.2 on 2025-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contacts_email_contacts_last_name_contacts_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده / نشده'),
        ),
    ]
