# Generated by Django 5.2 on 2025-11-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'تماس', 'verbose_name_plural': 'تماس ها'},
        ),
    ]
