# Generated by Django 5.2 on 2025-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contacts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.TextField(default=1, verbose_name='متن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
