# Generated by Django 5.2 on 2025-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=1, verbose_name='کامنت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='عکس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
    ]
