# Generated by Django 5.2 on 2025-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام مهارت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='value',
            field=models.TextField(default=1, verbose_name='مقدار'),
            preserve_default=False,
        ),
    ]
