# Generated by Django 5.2 on 2025-11-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_name_service_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_icon',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ایکون'),
        ),
    ]
