# Generated by Django 5.2 on 2025-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
        migrations.AddField(
            model_name='site',
            name='Team_email',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='Team_instagram',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='Team_telegram',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='about_work_keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='author_meta_tag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='description_home',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='description_meta_tag',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(upload_to='site_setting/images/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='keywords_meta_tag',
            field=models.CharField(max_length=255),
        ),
    ]
