# Generated by Django 5.2 on 2025-11-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'عضو', 'verbose_name_plural': 'اعضا'},
        ),
    ]
