# Generated by Django 5.2 on 2025-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_name_members_photo_members_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='members',
            name='skills',
            field=models.TextField(max_length=250, verbose_name='مهارت ها'),
        ),
        migrations.AlterField(
            model_name='members',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AlterField(
            model_name='members',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='لینک سایت'),
        ),
        migrations.AlterField(
            model_name='members',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='لینک واتساپ'),
        ),
    ]
