# Generated by Django 5.2 on 2025-11-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'درباره', 'verbose_name_plural': 'درباره'},
        ),
    ]
