# Generated by Django 5.2 on 2025-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='name',
            field=models.CharField(default=1, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='photo',
            field=models.ImageField(default=1, upload_to='members/', verbose_name='عکس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='skills',
            field=models.TextField(default=11, verbose_name='مهارت ها'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='telegram',
            field=models.URLField(default=1, verbose_name='لینک تلگرام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='website',
            field=models.URLField(default=1, verbose_name='لینک سایت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='whatsapp',
            field=models.URLField(default=1, verbose_name='لینک واتساپ'),
            preserve_default=False,
        ),
    ]
